using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MonitoringAgent.Common.Entities;

namespace MonitoringAgent.Data.Configurations;

/// <summary>
/// ============================================================================
/// Gateway Snapshot Entity Configuration
/// ============================================================================
///
/// Author: Roger Larson
/// Date: 06/07/2026
///
/// Configures Entity Framework mappings for gateway monitoring snapshots.
///
/// Gateway snapshots represent the health and availability of
/// monitored Ignition web gateways.
///
/// Collected Metrics:
/// - Reachability
/// - HTTP Status Code
/// - Response Time
///
/// Generated By:
/// - Monitoring Agent
///
/// Consumed By:
/// - HostOfflineMonitorWorker
/// - SnapshotAlertWorker
/// - AlertService
/// - Dashboard Metrics
///
/// Table:
///     gateway_snapshots
///
/// Relationships:
///
/// ServerService
///     ↓
/// GatewaySnapshots
///
/// ============================================================================
public sealed class GatewaySnapshotEntityConfiguration
    : IEntityTypeConfiguration<GatewaySnapshotEntity>
{
    public void Configure(
        EntityTypeBuilder<GatewaySnapshotEntity> builder)
    {
        // ---------------------------------------------------------------------
        // Table
        // ---------------------------------------------------------------------

        builder.ToTable(
            "gateway_snapshots");

        // ---------------------------------------------------------------------
        // Primary Key
        // ---------------------------------------------------------------------

        builder.HasKey(
            x => x.GatewaySnapshotId);

        builder.Property(
            x => x.GatewaySnapshotId)
            .HasColumnName(
                "gateway_snapshot_id");

        // ---------------------------------------------------------------------
        // Service Association
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.ServerServiceId)
            .HasColumnName(
                "server_service_id");

        // ---------------------------------------------------------------------
        // Snapshot Metadata
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.SnapshotUtc)
            .HasColumnName(
                "snapshot_utc");

        builder.Property(
            x => x.CreatedDateUtc)
            .HasColumnName(
                "created_date_utc");

        // ---------------------------------------------------------------------
        // Gateway Health Metrics
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.Reachable)
            .HasColumnName(
                "reachable");

        builder.Property(
            x => x.HttpStatusCode)
            .HasColumnName(
                "http_status_code");

        builder.Property(
            x => x.ResponseMs)
            .HasColumnName(
                "response_ms");

        // ---------------------------------------------------------------------
        // Relationships
        // ---------------------------------------------------------------------

        builder.HasOne(
                x => x.ServerService)
            .WithMany(
                x => x.GatewaySnapshots)
            .HasForeignKey(
                x => x.ServerServiceId);
    }
}