using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MonitoringAgent.Common.Entities;

namespace MonitoringAgent.Data.Configurations;

/// <summary>
/// ============================================================================
/// Ignition Snapshot Entity Configuration
/// ============================================================================
///
/// Author: Roger Larson
/// Date: 06/07/2026
///
/// Configures Entity Framework mappings for Ignition monitoring snapshots.
///
/// Ignition snapshots represent the health and operational status
/// of the Ignition platform running on a monitored server.
///
/// Collected Categories:
/// - Service Status
/// - Process Status
/// - Version Information
/// - CPU Utilization
/// - Memory Utilization
/// - Thread Counts
/// - Handle Counts
/// - Uptime Information
///
/// Generated By:
/// - Monitoring Agent
///
/// Consumed By:
/// - HostOfflineMonitorWorker
/// - SnapshotAlertWorker
/// - AlertService
/// - Dashboard Metrics
/// - Historical Charts
///
/// Table:
///     ignition_snapshots
///
/// Relationships:
///
/// ServerService
///     ↓
/// IgnitionSnapshots
///
/// ============================================================================
public sealed class IgnitionSnapshotEntityConfiguration
    : IEntityTypeConfiguration<IgnitionSnapshotEntity>
{
    public void Configure(
        EntityTypeBuilder<IgnitionSnapshotEntity> builder)
    {
        // ---------------------------------------------------------------------
        // Table
        // ---------------------------------------------------------------------

        builder.ToTable(
            "ignition_snapshots");

        // ---------------------------------------------------------------------
        // Primary Key
        // ---------------------------------------------------------------------

        builder.HasKey(
            x => x.IgnitionSnapshotId);

        builder.Property(
            x => x.IgnitionSnapshotId)
            .HasColumnName(
                "ignition_snapshot_id");

        // ---------------------------------------------------------------------
        // Service Association
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.ServerServiceId)
            .HasColumnName(
                "server_service_id");

        // ---------------------------------------------------------------------
        // Snapshot Metadata
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.SnapshotUtc)
            .HasColumnName(
                "snapshot_utc");

        builder.Property(
            x => x.CreatedDateUtc)
            .HasColumnName(
                "created_date_utc");

        // ---------------------------------------------------------------------
        // Service Health
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.ServiceRunning)
            .HasColumnName(
                "service_running");

        builder.Property(
            x => x.ProcessRunning)
            .HasColumnName(
                "process_running");

        // ---------------------------------------------------------------------
        // Version Information
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.IgnitionVersion)
            .HasColumnName(
                "ignition_version");

        builder.Property(
            x => x.JavaVersion)
            .HasColumnName(
                "java_version");

        // ---------------------------------------------------------------------
        // Resource Utilization
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.CpuPercent)
            .HasColumnName(
                "cpu_percent")
            .HasPrecision(9, 2);

        builder.Property(
            x => x.MemoryMb)
            .HasColumnName(
                "memory_mb");

        // ---------------------------------------------------------------------
        // Process Statistics
        // ---------------------------------------------------------------------

        builder.Property(
            x => x.ThreadCount)
            .HasColumnName(
                "thread_count");

        builder.Property(
            x => x.HandleCount)
            .HasColumnName(
                "handle_count");

        builder.Property(
            x => x.UptimeMinutes)
            .HasColumnName(
                "uptime_minutes");

        builder.Property(
            x => x.ProcessId)
            .HasColumnName(
                "process_id");

        builder.Property(
            x => x.ProcessName)
            .HasColumnName(
                "process_name");

        // ---------------------------------------------------------------------
        // Relationships
        // ---------------------------------------------------------------------

        builder.HasOne(
                x => x.ServerService)
            .WithMany(
                x => x.IgnitionSnapshots)
            .HasForeignKey(
                x => x.ServerServiceId);
    }
}