// ============================================================================
// Project: MonitoringAgent
// File: AlertEventEntity.cs
// Author: Roger Larson
// Date Created: 06/07/2026
// Date Updated: 06/07/2026
// Description:
//      Represents an alert event generated by the monitoring engine.
//
//      Alert events track the lifecycle of active and historical alerts,
//      including status transitions, acknowledgement activity, suppression
//      details, notification history, and alert occurrence information.
// ============================================================================

using MonitoringAgent.Common.Enums;

namespace MonitoringAgent.Common.Entities;

/// <summary>
/// Represents an alert generated by the monitoring engine.
/// </summary>
public sealed class AlertEventEntity
{
    // =====================================================================
    // Identity
    // =====================================================================

    /// <summary>
    /// Unique identifier for the alert event.
    /// </summary>
    public long AlertEventId
    {
        get;
        set;
    }

    /// <summary>
    /// Associated alert rule identifier.
    /// </summary>
    public int AlertRuleId
    {
        get;
        set;
    }

    /// <summary>
    /// Associated server identifier.
    /// </summary>
    public int ServerId
    {
        get;
        set;
    }

    /// <summary>
    /// Associated monitored service identifier, if applicable.
    /// </summary>
    public int? ServerServiceId
    {
        get;
        set;
    }

    // =====================================================================
    // Alert State
    // =====================================================================

    /// <summary>
    /// Current alert status.
    /// </summary>
    public AlertStatus Status
    {
        get;
        set;
    }

    /// <summary>
    /// Alert message presented to operators.
    /// </summary>
    public string Message
    {
        get;
        set;
    } = string.Empty;

    /// <summary>
    /// UTC timestamp when the alert was opened.
    /// </summary>
    public DateTime OpenedUtc
    {
        get;
        set;
    }

    /// <summary>
    /// UTC timestamp when the alert was first triggered.
    /// </summary>
    public DateTime? FirstTriggeredUtc
    {
        get;
        set;
    }

    /// <summary>
    /// UTC timestamp when the alert condition was last observed.
    /// </summary>
    public DateTime? LastSeenUtc
    {
        get;
        set;
    }

    /// <summary>
    /// Number of times the alert condition has been detected.
    /// </summary>
    public int OccurrenceCount
    {
        get;
        set;
    }

    // =====================================================================
    // Acknowledgement
    // =====================================================================

    /// <summary>
    /// UTC timestamp when the alert was acknowledged.
    /// </summary>
    public DateTime? AcknowledgedUtc
    {
        get;
        set;
    }

    /// <summary>
    /// User who acknowledged the alert.
    /// </summary>
    public string? AcknowledgedBy
    {
        get;
        set;
    }

    // =====================================================================
    // Suppression
    // =====================================================================

    /// <summary>
    /// UTC timestamp when the alert was suppressed.
    /// </summary>
    public DateTime? SuppressedUtc
    {
        get;
        set;
    }

    /// <summary>
    /// User who suppressed the alert.
    /// </summary>
    public string? SuppressedBy
    {
        get;
        set;
    }

    /// <summary>
    /// UTC timestamp when alert suppression expires.
    /// </summary>
    public DateTime? SuppressedUntilUtc
    {
        get;
        set;
    }

    // =====================================================================
    // Closure
    // =====================================================================

    /// <summary>
    /// UTC timestamp when the alert was closed.
    /// </summary>
    public DateTime? ClosedUtc
    {
        get;
        set;
    }

    /// <summary>
    /// User who closed the alert.
    /// </summary>
    public string? ClosedBy
    {
        get;
        set;
    }

    // =====================================================================
    // Notifications
    // =====================================================================

    /// <summary>
    /// UTC timestamp when the most recent notification was sent.
    /// </summary>
    public DateTime? LastNotificationUtc
    {
        get;
        set;
    }

    /// <summary>
    /// Total number of notifications sent for this alert.
    /// </summary>
    public int NotificationCount
    {
        get;
        set;
    }

    // =====================================================================
    // Navigation Properties
    // =====================================================================

    /// <summary>
    /// Associated alert rule.
    /// </summary>
    public AlertRuleEntity AlertRule
    {
        get;
        set;
    } = null!;

    /// <summary>
    /// Associated monitored server.
    /// </summary>
    public ServerEntity Server
    {
        get;
        set;
    } = null!;

    /// <summary>
    /// Associated monitored service.
    /// </summary>
    public ServerServiceEntity? ServerService
    {
        get;
        set;
    }
}