// ============================================================================
// Project: MonitoringAgent
// File: AlertRuleEntity.cs
// Author: Roger Larson
// Date Created: 06/07/2026
// Date Updated: 06/07/2026
// Description:
//      Represents an alert rule used by the monitoring engine to evaluate
//      collected metrics and determine when alerts should be generated.
//
//      Alert rules define threshold values, comparison operators, severity
//      levels, notification behavior, and automatic alert resolution
//      settings.
// ============================================================================

using MonitoringAgent.Common.Enums;

namespace MonitoringAgent.Common.Entities;

/// <summary>
/// Represents an alert rule used to evaluate monitored metrics.
/// </summary>
public sealed class AlertRuleEntity
{
    // =====================================================================
    // Identity
    // =====================================================================

    /// <summary>
    /// Unique identifier for the alert rule.
    /// </summary>
    public int AlertRuleId
    {
        get;
        set;
    }

    /// <summary>
    /// Display name of the alert rule.
    /// </summary>
    public string RuleName
    {
        get;
        set;
    } = string.Empty;

    // =====================================================================
    // Evaluation Criteria
    // =====================================================================

    /// <summary>
    /// Name of the metric evaluated by the rule.
    /// </summary>
    public string MetricName
    {
        get;
        set;
    } = string.Empty;

    /// <summary>
    /// Comparison operator used during rule evaluation.
    /// </summary>
    public AlertOperator Operator
    {
        get;
        set;
    }

    /// <summary>
    /// Threshold value used during rule evaluation.
    /// </summary>
    public decimal? ThresholdValue
    {
        get;
        set;
    }

    /// <summary>
    /// Severity assigned when the rule is triggered.
    /// </summary>
    public AlertSeverity Severity
    {
        get;
        set;
    }

    // =====================================================================
    // Alert Behavior
    // =====================================================================

    /// <summary>
    /// Indicates whether the rule is enabled.
    /// </summary>
    public bool Enabled
    {
        get;
        set;
    }

    /// <summary>
    /// Number of seconds the condition must remain active before an alert
    /// is generated.
    /// </summary>
    public int SustainSeconds
    {
        get;
        set;
    }

    /// <summary>
    /// Number of seconds between reminder notifications for active alerts.
    /// </summary>
    public int RepeatSeconds
    {
        get;
        set;
    }

    /// <summary>
    /// Indicates whether alerts generated by this rule are automatically
    /// closed when the condition clears.
    /// </summary>
    public bool AutoClose
    {
        get;
        set;
    }

    /// <summary>
    /// Indicates whether email notifications are enabled for this rule.
    /// </summary>
    public bool EmailEnabled
    {
        get;
        set;
    } = true;

    // =====================================================================
    // Audit Information
    // =====================================================================

    /// <summary>
    /// UTC timestamp when the rule was created.
    /// </summary>
    public DateTime CreatedDateUtc
    {
        get;
        set;
    }

    // =====================================================================
    // Navigation Properties
    // =====================================================================

    /// <summary>
    /// Alert events generated by this rule.
    /// </summary>
    public ICollection<AlertEventEntity>
        AlertEvents
    {
        get;
        set;
    } = new List<AlertEventEntity>();
}