// ============================================================================
// Project: MonitoringAgent
// File: EngineServiceEntity.cs
// Author: Roger Larson
// Date Created: 06/07/2026
// Date Updated: 06/07/2026
// Description:
//      Represents the runtime status and execution statistics of a
//      monitoring engine service or background worker.
//
//      Used to track worker health, execution history, performance metrics,
//      startup information, and error conditions for operational monitoring.
// ============================================================================

namespace MonitoringAgent.Common.Entities;

/// <summary>
/// Represents runtime status information for an engine service or worker.
/// </summary>
public sealed class EngineServiceEntity
{
    // =====================================================================
    // Identity
    // =====================================================================

    /// <summary>
    /// Unique identifier for the engine service record.
    /// </summary>
    public int EngineServiceId
    {
        get;
        set;
    }

    /// <summary>
    /// Name of the engine service or worker.
    /// </summary>
    public string ServiceName
    {
        get;
        set;
    } = string.Empty;

    /// <summary>
    /// Unique identifier for the current service instance.
    /// </summary>
    public Guid InstanceId
    {
        get;
        set;
    }

    // =====================================================================
    // Service Status
    // =====================================================================

    /// <summary>
    /// Current operational status of the service.
    /// </summary>
    public string Status
    {
        get;
        set;
    } = string.Empty;

    /// <summary>
    /// UTC timestamp when the service instance started.
    /// </summary>
    public DateTime StartedUtc
    {
        get;
        set;
    }

    /// <summary>
    /// UTC timestamp when the service last executed.
    /// </summary>
    public DateTime? LastRunUtc
    {
        get;
        set;
    }

    /// <summary>
    /// UTC timestamp when the most recent successful execution completed.
    /// </summary>
    public DateTime? LastSuccessUtc
    {
        get;
        set;
    }

    // =====================================================================
    // Execution Statistics
    // =====================================================================

    /// <summary>
    /// Total number of execution cycles performed.
    /// </summary>
    public long RunCount
    {
        get;
        set;
    }

    /// <summary>
    /// Total number of execution failures.
    /// </summary>
    public long ErrorCount
    {
        get;
        set;
    }

    /// <summary>
    /// Duration of the most recent execution cycle in milliseconds.
    /// </summary>
    public long? LastDurationMs
    {
        get;
        set;
    }

    // =====================================================================
    // Error Information
    // =====================================================================

    /// <summary>
    /// Most recent error message generated by the service.
    /// </summary>
    public string? LastError
    {
        get;
        set;
    }
}