// ============================================================================
// Project: MonitoringAgent.Data
// File: MonitoringDbContext.cs
// Author: Roger Larson
// Date Created: 06/07/2026
// Date Updated: 06/07/2026
// Description:
//      Entity Framework Core database context for the MonitoringAgent
//      platform.
//
//      Provides access to all monitoring entities and automatically
//      applies UTC DateTime value converters to ensure consistent
//      timestamp storage and retrieval throughout the application.
// ============================================================================

using Microsoft.EntityFrameworkCore;
using MonitoringAgent.Common.Entities;
using MonitoringAgent.Data.Converters;

namespace MonitoringAgent.Data;

/// <summary>
/// Entity Framework database context for the monitoring platform.
/// </summary>
public sealed class MonitoringDbContext
    : DbContext
{
    /// <summary>
    /// Initializes a new database context instance.
    /// </summary>
    /// <param name="options">
    /// Database context configuration options.
    /// </param>
    public MonitoringDbContext(
        DbContextOptions<MonitoringDbContext> options)
        : base(options)
    {
    }

    // =====================================================================
    // Core Monitoring
    // =====================================================================

    /// <summary>
    /// Monitored servers.
    /// </summary>
    public DbSet<ServerEntity> Servers =>
        Set<ServerEntity>();

    /// <summary>
    /// Historical host performance snapshots.
    /// </summary>
    public DbSet<HostSnapshotEntity> HostSnapshots =>
        Set<HostSnapshotEntity>();

    // =====================================================================
    // Service Catalog
    // =====================================================================

    /// <summary>
    /// Available service types.
    /// </summary>
    public DbSet<ServiceTypeEntity> ServiceTypes =>
        Set<ServiceTypeEntity>();

    /// <summary>
    /// Available monitored services.
    /// </summary>
    public DbSet<ServiceEntity> Services =>
        Set<ServiceEntity>();

    /// <summary>
    /// Services assigned to monitored servers.
    /// </summary>
    public DbSet<ServerServiceEntity> ServerServices =>
        Set<ServerServiceEntity>();

    // =====================================================================
    // Service Snapshots
    // =====================================================================

    /// <summary>
    /// Historical Ignition service snapshots.
    /// </summary>
    public DbSet<IgnitionSnapshotEntity> IgnitionSnapshots =>
        Set<IgnitionSnapshotEntity>();

    /// <summary>
    /// Historical gateway availability snapshots.
    /// </summary>
    public DbSet<GatewaySnapshotEntity> GatewaySnapshots =>
        Set<GatewaySnapshotEntity>();

    // =====================================================================
    // Alerting
    // =====================================================================

    /// <summary>
    /// Alert rule definitions.
    /// </summary>
    public DbSet<AlertRuleEntity> AlertRules =>
        Set<AlertRuleEntity>();

    /// <summary>
    /// Alert events generated by alert rules.
    /// </summary>
    public DbSet<AlertEventEntity> AlertEvents =>
        Set<AlertEventEntity>();

    // =====================================================================
    // Monitoring Engine
    // =====================================================================

    /// <summary>
    /// Monitoring engine service status records.
    /// </summary>
    public DbSet<EngineServiceEntity> EngineServices =>
        Set<EngineServiceEntity>();

    /// <summary>
    /// Configures entity mappings and model behavior.
    /// </summary>
    /// <param name="modelBuilder">
    /// Model builder used to configure entities.
    /// </param>
    protected override void OnModelCreating(
        ModelBuilder modelBuilder)
    {
        // Apply IEntityTypeConfiguration<T> classes
        // from this assembly automatically.
        modelBuilder.ApplyConfigurationsFromAssembly(
            typeof(MonitoringDbContext).Assembly);

        // Force all DateTime values to be stored and
        // retrieved as UTC timestamps.
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            foreach (var property in entityType.GetProperties())
            {
                if (property.ClrType == typeof(DateTime))
                {
                    property.SetValueConverter(
                        new UtcDateTimeConverter());
                }

                if (property.ClrType == typeof(DateTime?))
                {
                    property.SetValueConverter(
                        new NullableUtcDateTimeConverter());
                }
            }
        }

        base.OnModelCreating(
            modelBuilder);
    }
}