/*
===============================================================================
SnapshotGenerator
===============================================================================

Author: Roger Larson
Created: 06/07/2026

Purpose:
Generates realistic HealthSnapshot objects for use by the
MonitoringAgent Simulator.

Responsibilities:
- Create baseline healthy snapshots
- Apply simulation profile modifications
- Produce realistic monitoring data
- Simulate infrastructure failures
- Simulate resource exhaustion conditions

Supported Profiles:
- Healthy
- HighCpu
- HighMemory
- DiskFull
- GatewayDown
- IgnitionDown

Generation Strategy:
1. Create a healthy baseline snapshot
2. Apply profile-specific modifications
3. Return completed HealthSnapshot

Notes:
Snapshots generated by this service are intended to resemble
real-world monitoring data while remaining deterministic enough
for dashboard validation and alert testing.

The baseline snapshot represents a healthy Windows Server
running an Ignition gateway.

===============================================================================
*/

using MonitoringAgent.Common.Models;
using MonitoringAgent.Simulator.Enums;
using MonitoringAgent.Simulator.Models;

namespace MonitoringAgent.Simulator.Services;

/// <summary>
/// Generates realistic HealthSnapshots
/// for simulated servers.
/// </summary>
public static class SnapshotGenerator
{
    // -------------------------------------------------------------------------
    // Random Number Generator
    // -------------------------------------------------------------------------
    //
    // Used to generate realistic variability
    // across simulated metrics.
    //
    private static readonly Random Random =
        new();

    /// <summary>
    /// Creates a snapshot for the specified
    /// simulated server profile.
    ///
    /// Process:
    /// 1. Create healthy baseline snapshot
    /// 2. Apply profile-specific modifications
    /// 3. Return completed snapshot
    /// </summary>
    public static HealthSnapshot Create(
        SimulatedServer server)
    {
        // ---------------------------------------------------------------------
        // Healthy Baseline
        // ---------------------------------------------------------------------

        var snapshot =
            CreateHealthySnapshot(
                server.ServerName);

        // ---------------------------------------------------------------------
        // Profile Overrides
        // ---------------------------------------------------------------------

        switch (server.Profile)
        {
            // -------------------------------------------------------------
            // Simulate sustained CPU saturation.
            // -------------------------------------------------------------
            case SimulationProfile.HighCpu:

                snapshot.CpuPercent =
                    Random.Next(90, 100);

                break;

            // -------------------------------------------------------------
            // Simulate memory pressure.
            // -------------------------------------------------------------
            case SimulationProfile.HighMemory:

                snapshot.MemoryPercent =
                    Random.Next(95, 100);

                snapshot.AvailableMemoryMb =
                    Random.Next(100, 500);

                break;

            // -------------------------------------------------------------
            // Simulate low disk space conditions.
            // -------------------------------------------------------------
            case SimulationProfile.DiskFull:

                snapshot.DiskPercentUsed =
                    Random.Next(95, 100);

                snapshot.DiskFreeGb =
                    Random.Next(1, 5);

                break;

            // -------------------------------------------------------------
            // Simulate gateway connectivity failure.
            // -------------------------------------------------------------
            case SimulationProfile.GatewayDown:

                snapshot.GatewayReachable =
                    false;

                snapshot.GatewayHttpStatusCode =
                    503;

                snapshot.GatewayResponseMs =
                    0;

                break;

            // -------------------------------------------------------------
            // Simulate Ignition service outage.
            // -------------------------------------------------------------
            case SimulationProfile.IgnitionDown:

                snapshot.IgnitionServiceRunning =
                    false;

                snapshot.IgnitionProcessRunning =
                    false;

                snapshot.IgnitionCpuPercent =
                    0;

                snapshot.IgnitionMemoryMb =
                    0;

                break;
        }

        return snapshot;
    }

    /// <summary>
    /// Creates a healthy baseline snapshot.
    ///
    /// The returned snapshot represents a healthy
    /// Windows Server hosting an operational
    /// Ignition gateway.
    /// </summary>
    private static HealthSnapshot
        CreateHealthySnapshot(
            string serverName)
    {
        return new HealthSnapshot
        {
            // -----------------------------------------------------------------
            // Snapshot Metadata
            // -----------------------------------------------------------------

            SnapshotUtc =
                DateTime.UtcNow,

            ServerName =
                serverName,

            AgentVersion =
                "1.0.0",

            DomainName =
                "SIMULATOR",

            // -----------------------------------------------------------------
            // Host Metrics
            // -----------------------------------------------------------------

            CpuPercent =
                Random.Next(5, 25),

            MemoryPercent =
                Random.Next(25, 60),

            AvailableMemoryMb =
                Random.Next(4000, 12000),

            ProcessCount =
                Random.Next(100, 250),

            SystemUptimeMinutes =
                Random.Next(1000, 50000),

            ContextSwitchesPerSec =
                Random.Next(100, 500),

            PageFaultsPerSec =
                Random.Next(0, 10),

            // -----------------------------------------------------------------
            // Disk Metrics
            // -----------------------------------------------------------------

            SystemDrive =
                "C:",

            DiskPercentUsed =
                Random.Next(20, 70),

            DiskFreeGb =
                Random.Next(50, 500),

            DiskReadsPerSec =
                Random.Next(10, 500),

            DiskWritesPerSec =
                Random.Next(10, 500),

            DiskReadLatencyMs =
                Random.Next(1, 10),

            DiskWriteLatencyMs =
                Random.Next(1, 10),

            DiskQueueLength =
                Random.Next(0, 2),

            AvgDiskQueueLength =
                Random.Next(0, 2),

            // -----------------------------------------------------------------
            // Network Metrics
            // -----------------------------------------------------------------

            PrimaryNetworkInterface =
                "Ethernet0",

            NetworkBytesReceivedPerSec =
                Random.Next(1000, 50000),

            NetworkBytesSentPerSec =
                Random.Next(1000, 50000),

            TcpRetransmissionsPerSec =
                0,

            // -----------------------------------------------------------------
            // Gateway Metrics
            // -----------------------------------------------------------------

            GatewayReachable =
                true,

            GatewayHttpStatusCode =
                200,

            GatewayResponseMs =
                Random.Next(50, 300),

            // -----------------------------------------------------------------
            // Ignition Metrics
            // -----------------------------------------------------------------

            IgnitionServiceRunning =
                true,

            IgnitionProcessRunning =
                true,

            IgnitionVersion =
                "8.1.45",

            JavaVersion =
                "17.0.10",

            IgnitionCpuPercent =
                Random.Next(1, 20),

            IgnitionMemoryMb =
                Random.Next(1000, 4000),

            IgnitionThreadCount =
                Random.Next(100, 400),

            IgnitionHandleCount =
                Random.Next(200, 1000),

            IgnitionUptimeMinutes =
                Random.Next(1000, 50000),

            IgnitionProcessId =
                Random.Next(1000, 9999),

            IgnitionProcessName =
                "java",

            // -----------------------------------------------------------------
            // System Information
            // -----------------------------------------------------------------

            OperatingSystem =
                "Windows Server 2022",

            OperatingSystemVersion =
                "10.0",

            ProcessorCount =
                16,

            TotalMemoryMb =
                32768
        };
    }
}