/**
 * ============================================================================
 * Alert Rules Page
 * ============================================================================
 *
 * Author: Roger Larson
 * Date: 06/07/2026
 *
 * Purpose:
 * Configure monitoring and alert generation rules.
 *
 * Features:
 * - Create rules
 * - Edit rules
 * - Enable / disable rules
 * - Delete rules
 *
 * Notes:
 * Rules determine when alerts are generated by the monitoring engine.
 * Thresholds, severity, and notification behavior are configurable.
 * ============================================================================
 */

// Styles
import "./AlertRulesPage.css";

// React
import {
    useEffect,
    useState
} from "react";

// Models
import type {
    AlertRuleResponse
} from "../models/AlertRuleResponse";

// APIs
import {
    getAlertRules,
    deleteAlertRule,
    setRuleEnabled,
    createAlertRule,
    updateAlertRule
} from "../api/alertRuleApi";

// Components
import AlertRuleEditor
    from "../components/AlertRuleEditor";
import DashboardCard
    from "../components/DashboardCard";

// Navigation
import AppNav 
    from "../nav/AppNav";
import PageHeader
    from "../components/PageHeader";
import Footer
    from "../nav/Footer";
import {
    usePageTitle
}
from "../hooks/UsePageTitle";

/**
 * Alert Rules Page
 *
 * Allows administrators to:
 * - View configured alert rules
 * - Enable / disable rules
 * - Create new rules
 * - Edit existing rules
 * - Delete rules
 */
export default function AlertRulesPage() {

    // -------------------------------------------------------------------------
    // Page Title
    // -------------------------------------------------------------------------
    usePageTitle("Alert Rules");

    // -------------------------------------------------------------------------
    // State
    // -------------------------------------------------------------------------

    const [rules, setRules] =
        useState<AlertRuleResponse[]>([]);

    const [editingRule, setEditingRule] =
        useState<
            AlertRuleResponse | undefined
        >();

    const [showEditor, setShowEditor] =
        useState(false);

    // -------------------------------------------------------------------------
    // Data Loading
    // -------------------------------------------------------------------------

    const loadRules = async () => {

        const data =
            await getAlertRules();

        setRules(data);
    };

    // -------------------------------------------------------------------------
    // Initial Load
    // -------------------------------------------------------------------------

    useEffect(() => {

        loadRules();

    }, []);

    // -------------------------------------------------------------------------
    // Save Rule
    // -------------------------------------------------------------------------

    const saveRule = async (
        rule: AlertRuleResponse
    ) => {

        if (rule.alertRuleId === 0) {

            await createAlertRule(
                rule
            );
        }
        else {

            await updateAlertRule(
                rule
            );
        }

        setShowEditor(false);

        setEditingRule(
            undefined
        );

        await loadRules();
    };

    // -------------------------------------------------------------------------
    // Delete Rule
    // -------------------------------------------------------------------------

    const deleteRule = async (
        alertRuleId: number,
        ruleName: string
    ) => {

        const confirmed =
            window.confirm(
                `Delete alert rule "${ruleName}"?\n\nThis action cannot be undone.`
            );

        if (!confirmed) {
            return;
        }

        await deleteAlertRule(
            alertRuleId
        );

        await loadRules();
    };

    // -------------------------------------------------------------------------
    // Enable / Disable Rule
    // -------------------------------------------------------------------------

    const toggleRule = async (
        rule: AlertRuleResponse
    ) => {

        await setRuleEnabled(
            rule.alertRuleId,
            !rule.enabled
        );

        await loadRules();
    };

    // -------------------------------------------------------------------------
    // Create New Rule
    // -------------------------------------------------------------------------

    const createNewRule = () => {

        setEditingRule(
            undefined
        );

        setShowEditor(
            true
        );
    };

    // -------------------------------------------------------------------------
    // Edit Rule
    // -------------------------------------------------------------------------

    const editRule = (
        rule: AlertRuleResponse
    ) => {

        setEditingRule(
            rule
        );

        setShowEditor(
            true
        );
    };

    // -------------------------------------------------------------------------
    // Close Editor
    // -------------------------------------------------------------------------

    const closeEditor = () => {

        setShowEditor(
            false
        );

        setEditingRule(
            undefined
        );
    };

    // -------------------------------------------------------------------------
    // Rule Metrics
    // -------------------------------------------------------------------------

    const enabledRules =
        rules.filter(
            rule => rule.enabled
        );

    const disabledRules =
        rules.filter(
            rule => !rule.enabled
        );

    const criticalRules =
        rules.filter(
            rule =>
                rule.severity === "Critical"
        );

    const warningRules =
        rules.filter(
            rule =>
                rule.severity === "Warning"
        );

    // -------------------------------------------------------------------------
    // Render
    // -------------------------------------------------------------------------

    return (
        <div className="page">

            <AppNav />

            {/* -------------------------------------------------------------
                Header
               ------------------------------------------------------------- */}

            <PageHeader title="Alert Rules">
            </PageHeader>

            {/* -------------------------------------------------------------
                    Summary Cards
                ------------------------------------------------------------- */}

                <div className="alert-rules-summary">

                    <DashboardCard
                        title="Total Rules"
                        value={rules.length}
                    />

                    <DashboardCard
                        title="Enabled"
                        value={enabledRules.length}
                        statusClass="healthy"
                    />

                    <DashboardCard
                        title="Disabled"
                        value={disabledRules.length}
                        statusClass="offline"
                    />

                    <DashboardCard
                        title="Critical Rules"
                        value={criticalRules.length}
                        statusClass="critical"
                    />

                    <DashboardCard
                        title="Warning Rules"
                        value={warningRules.length}
                        statusClass="warning"
                    />

                </div>

            {/* -------------------------------------------------------------
                Toolbar
               ------------------------------------------------------------- */}

            <div className="alert-rules-toolbar">

                <button
                    onClick={
                        createNewRule
                    }
                >
                    New Rule
                </button>

            </div>

            {/* -------------------------------------------------------------
                Rules Table
               ------------------------------------------------------------- */}

            <table className="details-table">

                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Metric</th>
                        <th>Operator</th>
                        <th>Threshold</th>
                        <th>Severity</th>
                        <th>Enabled</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>

                    {rules.map(rule => (

                        <tr
                            key={
                                rule.alertRuleId
                            }
                        >
                            <td>
                                {rule.ruleName}
                            </td>

                            <td>
                                {rule.metricName}
                            </td>

                            <td>
                                {rule.operator}
                            </td>

                            <td>
                                {rule.threshold}
                            </td>

                            <td>
                                {rule.severity}
                            </td>

                            <td>

                                <input
                                    type="checkbox"
                                    checked={
                                        rule.enabled
                                    }
                                    onChange={() =>
                                        toggleRule(
                                            rule
                                        )
                                    }
                                />

                            </td>

                            <td>

                                <div className="alert-rule-actions">

                                    <button
                                        onClick={() =>
                                            editRule(
                                                rule
                                            )
                                        }
                                    >
                                        Edit
                                    </button>

                                    <button
                                        onClick={() =>
                                            deleteRule(
                                                rule.alertRuleId,
                                                rule.ruleName
                                            )
                                        }
                                    >
                                        Delete
                                    </button>

                                </div>

                            </td>

                        </tr>

                    ))}

                </tbody>

            </table>

            {/* -------------------------------------------------------------
                Rule Editor
               ------------------------------------------------------------- */}

            {showEditor && (

                <AlertRuleEditor
                    rule={editingRule}
                    onSave={saveRule}
                    onClose={closeEditor}
                />

            )}

            {/* -------------------------------------------------------------
            Footer
            ------------------------------------------------------------- */}
            <Footer />

        </div>
    );
}